spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&sessionVariables=character_set_client=utf8mb4,character_set_connection=utf8mb4,character_set_results=utf8mb4,time_zone='Asia/Seoul'
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: 'http://localhost:5173/login'
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: ${SERVER_PORT}
gcs:
  storage:
    bucket: ${GCP_BUCKET_NAME}
    credentials: gcs-key.json
    signed-url-expires-minutes: 10
    image-path:
      ai: ai/
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
firebase:
  service-account-key: ${FIREBASE_KEY_PATH}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api/v3/api-docs
khoa:
  api:
    key: ${KHOA_API_KEY}
seatrip:
  api:
    key: ${SEATRIP_API_KEY}
kma:
  api:
    key: ${KMA_API_KEY}

scheduler:
  tide:
    enabled: true
    today-cron: "0 0 2 * * ?" # 매일 새벽 2시 (오늘 데이터)
    monthly-cron: "0 0 1 1 * ?" # 매월 1일 새벽 1시 (월간 데이터)
    tomorrow-cron: "0 0 23 * * ?" # 매일 밤 11시 (내일 데이터)