spring:
  application:
    name: haeruhand
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
server:
  port: ${SERVER_PORT}
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
      image-path:
        ai: ai/
      image-url-prefix: "https://${AWS_BUCKET}.s3.${AWS_REGION}.amazonaws.com/"
      presigned-url-expires-minutes: 10
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}