version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: haeruhand-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.2
    container_name: haeruhand-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
